// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

type GlobalWithSupabase = typeof globalThis & {
  __supabase?: ReturnType<typeof createClient>;
};

const globalWithSupabase = globalThis as GlobalWithSupabase;

if (!globalWithSupabase.__supabase) {
  globalWithSupabase.__supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

export const supabase = globalWithSupabase.__supabase!;
